[workspace]
resolver = "2"
members = ["src-tauri"]

# https://v2.tauri.app/test/webdriver/example/#adding-tauri-to-the-cargo-project
[profile.release]
incremental = false
codegen-units = 1
panic = "abort"
opt-level = "s"
lto = true